[package]
name = "rust-grid-game"
version = "0.1.0"
authors = ["juanxjk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

piston = "0.52.1"
piston_window = "0.117.0"
